### ISSUE TITLE
[00:41:32 INFO]: /xxx lost connection: Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.tinyprotocol.packet.types.WrappedGameProfile

### ISSUE THREAD

**Issue by factrum** [funkemunky/Atlas#48] opened 2022-08-12 22:43 UTC
[00:41:32 INFO]: /xxx lost connection: Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class cc.funkemunky.api.tinyprotocol.packet.types.WrappedGameProfile

**Comment by Gyztor** [comment] 2022-08-13 18:44
duplicate of https://github.com/funkemunky/Atlas/issues/44
Edit: my bad. fixed it to be the correct one

**Comment by Gyztor** [comment] 2022-08-13 18:44
wait wrong one hold on

**Closed as completed** 2022-08-15 15:33 UTC

**Comment by mitchngwen** [comment] 2022-09-11 03:07
don't close it if it's not fixed dupe or no dupe
